[package]
name = "brasa_vm"
description.workspace = true
authors.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
brasa_bytecode = { workspace = true }
brasa_interp = { workspace = true }

[dev-dependencies]
brasa_source = { workspace = true }
brasa_parser = { workspace = true }
brasa_hir = { workspace = true }
brasa_resolver = { workspace = true }
brasa_typeck = { workspace = true }
brasa_codegen = { workspace = true }
criterion = { workspace = true }

[[bench]]
name = "backends"
harness = false
