[package]
name = "brasa"
description.workspace = true
authors.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true

[[bin]]
name = "brasa"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
brasa_parser = { workspace = true }
brasa_diagnostics = { workspace = true }
