[package]
name = "brasa_typeck"
authors.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
brasa_arena = { workspace = true }
brasa_source = { workspace = true }
brasa_hir = { workspace = true }
brasa_resolver = { workspace = true }
brasa_diagnostics = { workspace = true }

[dev-dependencies]
brasa_parser = { workspace = true }
insta = { workspace = true }
